
title: Kolum Cosmas
logo: /pngasset/Screenshot 2025-10-28 103423.png
description: Data Scientist | Data Analytics using Python, MySQL, Excel, Power BI and Tableau
show_downloads: true
theme: jekyll-theme-minimal
