title: Kolum Cosmas 
logo: /assets/img/headshot_circle.png
#description: text below image
##Mission 
To harness the power of data science and analytics to drive transformative solutions through innovation.
show_downloads: true
theme: jekyll-theme-minimal
